wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.4
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    m:
    - 1: trainer/global_step
      6:
      - 3
    - 1: gradients/graph_1model\.fc2\.bias._type
      5: 1
      6:
      - 1
    - 1: gradients/graph_1model\.fc2\.bias.values
      5: 1
      6:
      - 1
    - 1: gradients/graph_1model\.fc2\.bias.bins
      5: 1
      6:
      - 1
    - 1: gradients/graph_1model\.fc2\.weight._type
      5: 1
      6:
      - 1
    - 1: gradients/graph_1model\.fc2\.weight.values
      5: 1
      6:
      - 1
    - 1: gradients/graph_1model\.fc2\.weight.bins
      5: 1
      6:
      - 1
    - 1: gradients/graph_1model\.fc1\.bias._type
      5: 1
      6:
      - 1
    - 1: gradients/graph_1model\.fc1\.bias.values
      5: 1
      6:
      - 1
    - 1: gradients/graph_1model\.fc1\.bias.bins
      5: 1
      6:
      - 1
    - 1: gradients/graph_1model\.fc1\.weight._type
      5: 1
      6:
      - 1
    - 1: gradients/graph_1model\.fc1\.weight.values
      5: 1
      6:
      - 1
    - 1: gradients/graph_1model\.fc1\.weight.bins
      5: 1
      6:
      - 1
    - 1: gradients/graph_1model\.cell_list\.1\.conv_can\.weight._type
      5: 1
      6:
      - 1
    - 1: gradients/graph_1model\.cell_list\.1\.conv_can\.weight.values
      5: 1
      6:
      - 1
    - 1: gradients/graph_1model\.cell_list\.1\.conv_can\.weight.bins
      5: 1
      6:
      - 1
    - 1: gradients/graph_1model\.cell_list\.1\.conv_gates\.weight._type
      5: 1
      6:
      - 1
    - 1: gradients/graph_1model\.cell_list\.1\.conv_gates\.weight.values
      5: 1
      6:
      - 1
    - 1: gradients/graph_1model\.cell_list\.1\.conv_gates\.weight.bins
      5: 1
      6:
      - 1
    - 1: gradients/graph_1model\.cell_list\.2\.conv_can\.weight._type
      5: 1
      6:
      - 1
    - 1: gradients/graph_1model\.cell_list\.2\.conv_can\.weight.values
      5: 1
      6:
      - 1
    - 1: gradients/graph_1model\.cell_list\.2\.conv_can\.weight.bins
      5: 1
      6:
      - 1
    - 1: gradients/graph_1model\.cell_list\.2\.conv_gates\.weight._type
      5: 1
      6:
      - 1
    - 1: gradients/graph_1model\.cell_list\.2\.conv_gates\.weight.values
      5: 1
      6:
      - 1
    - 1: gradients/graph_1model\.cell_list\.2\.conv_gates\.weight.bins
      5: 1
      6:
      - 1
    - 1: gradients/graph_1model\.cell_list\.0\.conv_can\.weight._type
      5: 1
      6:
      - 1
    - 1: gradients/graph_1model\.cell_list\.0\.conv_can\.weight.values
      5: 1
      6:
      - 1
    - 1: gradients/graph_1model\.cell_list\.0\.conv_can\.weight.bins
      5: 1
      6:
      - 1
    - 1: gradients/graph_1model\.cell_list\.0\.conv_gates\.weight._type
      5: 1
      6:
      - 1
    - 1: gradients/graph_1model\.cell_list\.0\.conv_gates\.weight.values
      5: 1
      6:
      - 1
    - 1: gradients/graph_1model\.cell_list\.0\.conv_gates\.weight.bins
      5: 1
      6:
      - 1
    - 1: train_loss
      5: 1
      6:
      - 1
    - 1: amb_match_test_acc
      5: 1
      6:
      - 1
    - 1: epoch
      5: 1
      6:
      - 1
    - 1: clean_mismatch_test_acc
      5: 1
      6:
      - 1
    - 1: amb_mismatch_test_acc
      5: 1
      6:
      - 1
    - 1: val_loss
      5: 1
      6:
      - 1
    python_version: 3.9.12
    start_time: 1691019166.138679
    t:
      1:
      - 1
      - 9
      - 35
      - 41
      - 55
      2:
      - 1
      - 9
      - 35
      - 41
      - 55
      3:
      - 1
      - 2
      - 7
      - 23
      4: 3.9.12
      5: 0.13.4
      8:
      - 5
